apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    domain: devops
    component: api
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        domain: devops
        component: api
    spec:
      containers:
      - name: chillastic
        image: groupbyinc/chillastic
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
        env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: '6379'