apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chillastic
  labels:
    domain: devops
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        domain: devops
        name: chillastic
    spec:
      containers:
      - name: chillastic
        image: groupbyinc/chillastic:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
        env:
          - name: REDIS_HOST
            value: chillastic-redis.default.svc.cluster.local
          - name: REDIS_PORT
            value: '6379'